Repository idtlab/AIDRIN, pull requests merged in 2025-08, with the labels that each got.

#36 Add dynamic versioning via setuptools and expose docs link in app
  README.md
  aidrin/templates/homepage.html
  aidrin/templates/universalComponents.html
  pyproject.toml
Labels: type: documentation, priority: high, type: frontend, dependencies

#39 correct project.version to use dynamic attr
  pyproject.toml
Labels: type: bug, priority: high, dependencies

#40 include build tests in CI
  .github/workflows/build.yml
Labels: type: CI, type: tests, priority: medium

#38 include requirements.txt
  requirements.txt
Labels: priority: high, dependencies
